network: SWIN
input_size:
  height: 384
  width: 384
SATRN:
  encoder:
    hidden_dim: 300
    filter_dim: 600
    layer_num: 6
    head_num: 8
  decoder:
    src_dim: 1024
    hidden_dim: 512
    filter_dim: 512
    layer_num: 4
    head_num: 8
checkpoint: ""
prefix: "./log/swin"

data:
  train:
    - "/opt/ml/input/data/train_dataset/gt.txt"
  test:
    - ""
  token_paths:
    - "/opt/ml/input/data/train_dataset/tokens.txt"  # 241 tokens
  fold: 0
  crop: True
  rgb: 3    # 3 for color, 1 for greyscale
  
batch_size: 16
num_workers: 8
num_epochs: 50
print_epochs: 1
dropout_rate: 0.1
teacher_forcing_ratio:
  tf_max: 0.8
  tf_min: 0.3
max_grad_norm: 2.0
seed: 21
scheduler:
  scheduler: 'CustomCosine'
  cycle: 1
  warmup_ratio: 0.1
optimizer:
  optimizer: 'AdamW' # Adam, Adadelta
  lr: 1e-4 # 1e-4
  weight_decay: 1e-4
  is_cycle: True
  enc_lr: 5e-4
  dec_lr: 5e-4
